### PR TITLE
fix: empty list view

### LINKED ISSUE #744: Empty List View Component
**Description**
Passing in no children into the list view component should show an empty state it instead shows undefined. If I pass in an empty array it then behaves as expected. 

renderEmptyState prop is also not implemented for this component. Can separate into another ticket if needed but from the spectrum docs users should be able to display something else like an IllustratedMessage to indicate that the list is empty rather than just showing an empty list.

https://react-spectrum.adobe.com/react-spectrum/ListView.html#empty-state

**Steps to reproduce**

- Passing in no children
```
from deephaven import ui


@ui.component
def ui_list_view():
    empty_list = ui.list_view()

    return empty_list


lv = ui_list_view()
```

- Passing in empty array
```
from deephaven import ui


@ui.component
def ui_list_view():
    empty_list = ui.list_view(
        []
    )

    return empty_list


lv = ui_list_view()
```

- renderEmptyState
```
from deephaven import ui


@ui.component
def ui_list_view():
    value, set_value = ui.use_state(["Text 2"])

    error_message = ui.illustrated_message(
        ui.icon("vsWarning"),
        ui.heading("Invalid Input"),
        ui.content("Please enter 'Sym' and 'Exchange' above"),
    )

    empty_list = ui.list_view(
        [],
        render_empty_state=error_message
    )

    return empty_list


lv = ui_list_view()
```

**Expected results**
- Passing in no children or empty array
image

- renderEmptyState from Spectrum docs
image

**Actual results**
- Passing in no children
image

- Passing in empty array
image

- renderEmptyState
image

**Additional details and attachments**

**Versions**
Engine Version: 0.36.0-SNAPSHOT
Web UI Version: 0.88.0
Java Version: 21.0.4
Barrage Version: 0.6.0
Browser Name: Microsoft Edge 127
OS Name: macOS 10.15.7
@deephaven/js-plugin-plotly-express: 0.11.2
@deephaven/js-plugin-matplotlib: 0.5.0
@deephaven/js-plugin-ui: 0.19.0

 - Engine Version: ...
 - Web UI Version: ...
 - Java Version: ...
 - Barrage Version: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

### PR DESCRIPTION
**Pull request by wusteven815**
- Fixes #744 
  - Update props types to convert `renderEmptyState` from `Element` in Python to `() => Element` in TypeScript
  - Throw error if `children` is undefined

### CODE REVIEW

**Comment by wusteven815** [comment]
- For `children`, there seems to be a type mismatch between the input and output props
- For `renderEmptyState`, the Python input is type `Element` whereas the TypeScript side expects `() => Element`

File: plugins/ui/src/js/src/elements/ListView.tsx [hunk 1]
```diff
@@ -17,6 +17,10 @@ export function ListView(props: SerializedListViewProps): JSX.Element | null {
   const isObjectView = isElementOfType(children, ObjectView);
   const table = useReExportedTable(children);
 
+  if (children == null) {
+    throw new Error('Children must be defined for list_view.');
+  }
+
```
Comment (mofojed) [inline plugins/ui/src/js/src/elements/ListView.tsx:23]: `assertNotNull` is a utility function that does this check

**Review by mofojed — APPROVED** [review]

**Review by mofojed — APPROVED** [review]
