### PR TITLE
fix: invalid ui.panel usage should result in clear error

### LINKED ISSUE #640: Deephaven UI - Invalid ui.panel usage should show clear error
ui.panel should only be used at the top level of a component or when layout out a ui.dashboard.

e.g. This is invalid:
```python
import deephaven.ui as ui
 
 
@ui.component
def test_component():
    # ui.flex parent should be invalid
    return ui.flex(
        ui.panel(
            "Panel A",
            title = "Panel A",),
        ui.panel(
            "Panel B",
            title = "Panel B",),
        direction = "row"
    )
 
 
t1 = test_component()
```

This seems to run but produces an additional empty panel for `t1`
image

We should explicitly show an error when panels are wrapped in invalid parents.

### PR DESCRIPTION
**Pull request by AkshatJawne**
Closes #640

### CODE REVIEW

File: plugins/ui/src/js/src/layout/ReactPanel.tsx [hunk 1]
```diff
@@ -97,6 +97,12 @@ function ReactPanel({
   const contentKey = useMemo(() => nanoid(), [metadata]);
 
   const parent = useParentItem();
+  const contextPanelId = usePanelId();
+  if (contextPanelId != null) {
+    throw new Error(
```
Comment (mofojed) [inline plugins/ui/src/js/src/layout/ReactPanel.tsx:102]: We have specific error types thrown for other similar errors, e.g. `MixedPanelsError` and `NoChildrenError`. Create a new error type similar to those (e.g. `NestedPanelError`) and throw it

**Review by mofojed — CHANGES_REQUESTED** [review]
