### PR TITLE
fix: slider input default value

### LINKED ISSUE #754: ui.slider and ui.range_slider not updating default_value
**Description**

Both `ui.slider` and `ui.range_slider` are not updating default_value when snippets creating them are reran.

How to solve: Will use useDebouncedOnChange value that we used for `ui.text_area` and `ui.text_field`

**Steps to reproduce**

1. Create slider with following snippet:

```
from deephaven import ui

my_slider_basic = ui.slider(default_value=20, label="Test")
```

2. Change `default_value` from 20 to 30
3. Rerun snippet

**Expected results**

The default value for both should update when rerunning the code to the new numeric values.

**Actual results**

The `slider` and `range_slider` both do not update, keeping their old values.

**Versions**

Engine Version: 0.37.0-SNAPSHOT
Web UI Version: 0.89.0
Java Version: 21.0.4
Barrage Version: 0.6.0
Browser Name: Chrome 127
OS Name: macOS 10.15.7
@deephaven/js-plugin-plotly-express: 0.11.2
@deephaven/js-plugin-ui: 0.19.0
@deephaven/js-plugin-matplotlib: 0.5.0

### PR DESCRIPTION
**Pull request by wusteven815**
- Fixes #754 
- Change slider to use `useDebouncedOnChange`

### CODE REVIEW

File: plugins/ui/src/js/src/elements/model/SerializedPropTypes.ts [hunk 1]
```diff
@@ -44,24 +44,24 @@ export type SerializedPressEventProps<T> = Omit<
...
 };
 
-export type SerializedInputElementProps<T> = Omit<
+export type SerializedInputElementProps<T, V> = Omit<
   T,
   'defaultValue' | 'value' | 'onChange'
 > & {
   /** The default value of the input */
-  defaultValue?: string;
+  defaultValue?: V;
```
Comment (mattrunyon) [inline plugins/ui/src/js/src/elements/model/SerializedPropTypes.ts:52]: Why change this to a generic? What other value could `defaultValue` and `value` have that is valid except for string?

Comment (wusteven815) [reply plugins/ui/src/js/src/elements/model/SerializedPropTypes.ts:52]: `{ start: number; end: number }` for sliders
