### PR TITLE
fix: Deephaven express chart title does not update dynamically

### LINKED ISSUE #377: Deephaven express chart title does not update dynamically
**Description**

When creating a Deephaven express chart using deephaven.ui, the title is not updating dynamically.

**Steps to reproduce**
1. Create the following component:
```
from deephaven import ui
from deephaven.plot import express as dx


@ui.component
def ui_stock_widget_plot(source, default_sym="", default_exchange=""):
    sym, set_sym = ui.use_state(default_sym)
    exchange, set_exchange = ui.use_state(default_exchange)

    ti1 = ui.text_field(
        label="Sym", label_position="side", value=sym, on_change=set_sym
    )
    ti2 = ui.text_field(
        label="Exchange", label_position="side", value=exchange, on_change=set_exchange
    )
    t1 = source.where([f"sym=`{sym.upper()}`", f"exchange=`{exchange}`"])
    p = dx.line(table=t1, x="timestamp", y="price", title=f"{sym}-{exchange}")

    return ui.flex(ui.flex(ti1, ti2), t1, p, direction="column", flex_grow=1)


my_stock_widget_plot = ui_stock_widget_plot(stocks, "CAT", "TPET")
```
2. Change the Sym or Exchange

**Expected results**
2. The contents and title of the chart should update

**Actual results**
2. The contents update, but the title does not

**Additional details and attachments**

image

**Versions**

Engine Version: 0.34.0-SNAPSHOT
Web UI Version: 0.69.1
Java Version: 21.0.2
Barrage Version: 0.6.0
Browser Name: Chrome 123
OS Name: macOS 10.15.7

### PR DESCRIPTION
**Pull request by mattrunyon**
Fixes #377

The issue was the widget changing and thus the model changing, but the `Chart` component was not resetting. `Chart` puts the model layout into its state, so it wasn't updating when the model changed. This could also be fixed in `Chart`, but this is the simplest fix for the dh.ui scenario in the ticket.

This does not fix a scenario where deephaven-express sends a new title (no widget change) as part of an update as `Chart` will still keep its layout over the model's layout in that case. AFAIK there's currently no way to do this though

### CODE REVIEW

File: plugins/plotly-express/src/js/src/PlotlyExpressChart.tsx [hunk 1]
```diff
@@ -14,13 +14,15 @@ export function PlotlyExpressChart(
   const { fetch } = props;
   const containerRef = useRef<HTMLDivElement>(null);
   const [model, setModel] = useState<PlotlyExpressChartModel>();
+  const [widgetRevision, setWidgetRevision] = useState(0); // Used to force a clean chart state on widget change
```
Comment (mofojed) [inline plugins/plotly-express/src/js/src/PlotlyExpressChart.tsx:17]: Do we not get a descriptor in props as well? Pattern I've used elsewhere is memoize on the descriptor to generate a shortid for the element.

Though this seems fine.

**Review by mofojed — APPROVED** [review]

File: plugins/plotly-express/src/js/src/PlotlyExpressChart.tsx (hunk 1 above)
Comment (mattrunyon) [reply plugins/plotly-express/src/js/src/PlotlyExpressChart.tsx:17]: In the types we only have `fetch` in `WidgetComponentProps`. The panel gets the metadata descriptor, but when it's used in dh.ui, the metadata is for the dh.ui widget, not the plotly widget

**Comment by mattrunyon** [comment]
Removed from the panel version because it was failing CI, but working locally. I checked and `ChartPanel` should handle the scenario where `makeModel` change properly. It will unmount the `Chart` component while loading so it should always be a clean state there

**Review by mofojed — APPROVED** [review]
