### PR TITLE
fix: icons in illustrated message

### LINKED ISSUE #558: Default to `size="XXL"` and `marginBottom="size-10"` when `Icon` is a child of `IllustratedMessage`
When using an `Icon` in an `IllustratedMessage`, we should automatically set the default `size` to `XXL` and `marginBottom` to `size-10` if the user has not specified those.
Should be able to create a wrapper `IllustratedMessage` component that checks the `Icon` children and adds the appropriate props before rendering the children.
Alternatively we may be able to simply set the `slot` prop so that it's an `illustration` in the `Icon`, and that may make everything work correctly: https://github.com/adobe/react-spectrum/blob/4a8b24028308831a06a2450e6975b8816406315f/packages/%40react-spectrum/icon/src/Illustration.tsx#L44
https://github.com/adobe/react-spectrum/blob/4a8b24028308831a06a2450e6975b8816406315f/packages/%40react-spectrum/illustratedmessage/src/IllustratedMessage.tsx#L22

### PR DESCRIPTION
**Pull request by ethanalvizo**
Closes #558

### CODE REVIEW

**Review by mofojed — CHANGES_REQUESTED** [review]
Merge the latest `main` into this branch so the diff is clear, right now it's including the changes from #532.

Works well but needs cleanup.

File: plugins/ui/src/js/src/elements/IllustratedMessage.tsx [hunk 1]
```diff
@@ -0,0 +1,44 @@
+import React from 'react';
+import {
+  IllustratedMessage as DHCAIllustratedMessage,
+  IllustratedMessageProps as DHCAIllustratedMessageProps,
```
Comment (mofojed) [inline plugins/ui/src/js/src/elements/IllustratedMessage.tsx:4]: Unsure what the A in DHCA stands for here? Should just be DHC:
```suggestion
  IllustratedMessage as DHCIllustratedMessage,
  IllustratedMessageProps as DHCIllustratedMessageProps,
```

File: plugins/ui/src/js/src/elements/IllustratedMessage.tsx [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+  props: DHCAIllustratedMessageProps
+): JSX.Element {
+  const { children, ...otherProps } = props;
+
+  /* eslint-disable-next-line react/jsx-props-no-spreading */
+  if (children === undefined) return <DHCAIllustratedMessage {...props} />;
+
+  const newChildren = React.Children.map(children, element => {
+    if (isElementOfType(element, Icon) === true) {
+      const size = element.props.size ?? 'XL';
```
Comment (mofojed) [inline plugins/ui/src/js/src/elements/IllustratedMessage.tsx:19]: Size should be XXL, not XL
```suggestion
      const size = element.props.size ?? 'XXL';
```

File: plugins/ui/src/deephaven/ui/components/illustrated_message.py [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+        is_hidden: Hides the element.
+        id: The unique identifier of the element.
+        UNSAFE_class_name: Set the CSS className for the element. Only use as a last resort. Use style props instead.
+        UNSAFE_style: Set the inline style for the element. Only use as a last resort. Use style props instead.
+
+    Examples:
+        prompt = ui.illustrated_message(
+            ui.heading("Enter URL above"),
+            ui.content("Enter a URL of a CSV above and click 'Load' to load it"),
+        )
```
Comment (mofojed) [inline plugins/ui/src/deephaven/ui/components/illustrated_message.py:106]: Let's make these examples more broad. Taking some inspiration from the examples on https://react-spectrum.adobe.com/react-spectrum/IllustratedMessage.html
```suggestion
        no_results = ui.illustrated_message(
            ui.heading("No Results"),
            ui.content("Try another search"),
        )
```

File: plugins/ui/src/deephaven/ui/components/illustrated_message.py [hunk 4]
```diff
@@ -0,0 +1,160 @@
...
+        warning = ui.illustrated_message(
+            ui.icon("vsWarning"),
+            ui.heading("Warning"),
+            ui.content("This is a warning message."),
+        )
+        error_message = ui.illustrated_message(
+            ui.icon("vsWarning", size="XXL", margin_bottom="size-10"),
+            ui.heading("Invalid Input"),
+            ui.content("Please enter 'Sym' and 'Exchange' above"),
+        )
```
Comment (mofojed) [inline plugins/ui/src/deephaven/ui/components/illustrated_message.py:116]: Don't need to specify the `size`/`margin_bottom` anymore. Can make this example more broad as well.
```suggestion
        error_message = ui.illustrated_message(
            ui.icon("vsError"),
            ui.heading("Access denied"),
            ui.content("You do not have permissions to access this page."),
        )
```

File: plugins/ui/src/deephaven/ui/components/illustrated_message.py [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+    Examples:
+        prompt = ui.illustrated_message(
+            ui.heading("Enter URL above"),
+            ui.content("Enter a URL of a CSV above and click 'Load' to load it"),
+        )
+        warning = ui.illustrated_message(
+            ui.icon("vsWarning"),
+            ui.heading("Warning"),
+            ui.content("This is a warning message."),
+        )
```
Comment (mofojed) [inline plugins/ui/src/deephaven/ui/components/illustrated_message.py:111]:
```suggestion
        warning = ui.illustrated_message(
            ui.icon("vsWarning"),
            ui.heading("Invalid input"),
            ui.content("No special characters allowed."),
        )
```

**Review by mofojed — CHANGES_REQUESTED** [review]

**Review by mofojed — APPROVED** [review]
