### PR TITLE
fix: Version bump + loading spinner fixes

### LINKED ISSUE #241: Infinite loading spinner when upgrading plotly express DH dependencies to 0.60.0
**Description**

Upgrading Plotly express plugin dependencies to DH 0.60.0 causes the loading spinner to never go away.

**Steps to reproduce**
- Upgrade dh dependencies to `0.60.0` in `plugins/plotly-express/src/js/package.json`
- Run the plugins repo locally via `npm start`
- Configure proxy port `VITE_JS_PLUGINS_DEV_PORT=4100` in DHC `packages/code-studio/.env.development.local`
- Run the following code:
```
from deephaven import empty_table
import deephaven.plot.express as dx

y = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K']

data = map(
    lambda x,i: f"{x}=X*EvenOdd+{i * 20}",
    y,
    range(len(y)))

t = empty_table(100).update([
    "X=ii",
    "EvenOdd = X % 2 / 4",
    ] + list(data))

p1 = dx.line(t, x="X", y=y)
```

**Expected results**

Loading spinner on chart should go away after data is loaded

**Actual results**

Loading spinner stays forever

**Additional details and attachments**

This seems to have been introduced by https://github.com/deephaven/web-client-ui/pull/1729/files , but the underlying issue seems to be we are never firing the `EVENT_LOADFINISHED` event from plotly express.

**Versions**

Web UI Version: 0.60.0

### PR DESCRIPTION
**Pull request by bmingles**
- DHC version bump
- Fixed infinite loading spinner
 
fixes #241

### CODE REVIEW

File: plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts [hunk 1]
```diff
@@ -58,6 +58,11 @@ export class PlotlyExpressChartModel extends ChartModel {
 
   widgetUnsubscribe?: () => void;
 
+  /**
+   * Set containing table IDs that are pending data.
+   */
+  tablesPendingData = new Set<number>();
+
```
Comment (mattrunyon) [inline plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts:65]: We should remove the id from this set in `removeTable`. Just in case we get into some weird situation where the server tells us about a table and then immediately tells us to forget it and we don't end up with data for some reason. I think it's highly unlikely, but just in case

File: plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts [hunk 2]
```diff
@@ -269,12 +274,18 @@ export class PlotlyExpressChartModel extends ChartModel {
...
     if (this.isPaused) {
       this.hasPendingUpdate = true;
       return;
     }
 
-    this.fireUpdate(this.getData());
+    if (this.tablesPendingData.size === 0) {
+      this.fireUpdate(this.getData());
+      this.fireLoadFinished();
+    }
```
Comment (mattrunyon) [inline plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts:288]: This might cause issues with plot_by if it's checked every time new data arrives. We could have a scenario where tables are added and removed almost every tick like the following. The layered plot has new tables added every second (from the UI perspective) because of the partitions changing.

Might need to add something to check if we ever finished loading or only track the initial tables for either data or removal and then after that just consider any state as already loaded and fire the updates on every data received.

```python
import deephaven.plot.express as dx
from deephaven import time_table
import random 

sourceh = time_table("PT1S").update(formulas=[
    "X = (int)random.gauss(20, 5)", 
    "Y = (int)random.gauss(20, 5)", 
    "Z = (float)random.gauss(30, 3)",
    "l1 = i % 20",
    "l2 = i % 30",
    ]).tail(10)

fig1 = dx.scatter(sourceh, x="Z", y="Y",
    by="l1",
    color_discrete_sequence=["lemonchiffon"]
)

fig2 = dx.scatter(sourceh, x="Z", y="Y",
    by="l2",
    color_discrete_sequence=["salmon"]
)

layered = dx.layer(fig1, fig2)
```

**Review by mattrunyon — CHANGES_REQUESTED** [review]

File: plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts (hunk 2 above)
Comment (bmingles) [reply plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts:288]: @mattrunyon  I don't see this example causing any trouble when I run it. Is there some specific problem you are expecting to see?

File: plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts (hunk 1 above)
Comment (bmingles) [reply plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts:65]: Good catch. Fixed

File: plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts (hunk 2 above)
Comment (mattrunyon) [reply plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts:288]: Possibly that we skip rendering an update after the load is finished because we've added another table but haven't received data from it yet.

This also adds more overhead from adding a `fireLoadFinished` to each update. It should effectively be a no-op because at the end of the day it just calls `setState` w/ an equivalent state, but no need for the overhead

**Review by mattrunyon — APPROVED** [review]

**Review by mattrunyon — APPROVED** [review]

**Review by mattrunyon — APPROVED** [review]
